### ISSUE TITLE
JWT package update

### ISSUE THREAD

**Issue by heshanh** [calcinai/oauth2-xero#17]
Hi, i was wondering if you're planning on updating `firebase/php-jwt` to the latest?

**Comment by sethsandaru** [comment]
bump for this

**Comment by calcinai** [comment]
Hi @heshanh & @sethsandaru apologies I haven't had a chance to test this out.  Have either of you tested the latest version?

**Comment by ok200paul** [comment]
> Hi, i was wondering if you're planning on updating `firebase/php-jwt` to the latest?

Hey @heshanh - long time no see man! Hope you're well. 

Anyway @calcinai thanks for a great package, I've set up calcinai/xero-php locally with an updated symlinked repo for calcinai/oauth2-xero - I've popped in a PR https://github.com/calcinai/oauth2-xero/pull/19 

I forked calcinai/xero-php to https://github.com/ok200paul/xero-php and referenced my updated fork, I'm on PHP8.1 so updated the PHPUnit dep to latest, and updated the tests to work with the PHPUnit version - they look good. Likely got some BC breaks so I didn't submit a PR here, but feel free to clone and run tests in there, hopefully they prove the firebase/php-jwt bump to this new version works OK.

**Comment by Rincewindrunner** [comment]
My colleague and I have had a look at the `firebase/php-jwt` changes (which don't look to impact the use cases this repo relies on the library for) and have been testing the updated version with no issues.

This and `calcinai/xero-php` are really helpful packages. I'm honestly surprised there hasn't been more noise on this issue - I landed here because this dependency is preventing us from updating to Laravel 9 LTS (where Laravel Passport requires the newer `firebase/php-jwt` version).
Would love to see it get updated here rather than also needing to fork the library in the interim.
Let me know if there is anything further we can do to help.

**Comment by calcinai** [comment]
Hey @Rincewindrunner sorry for the slow response. Feel free to make a PR from your fork and I'll merge it in.

**Comment by Rincewindrunner** [comment]
Sorry for my glacially slow PR, I've opened #21

**Comment by calcinai** [comment]
Hey, I can be slower...
